config/routes.rb
ClauseLogicDocumentation::Application.routes.draw do

  namespace "v1" do
    root :to => "welcome#index"

    # Resource Objects Documentation
    get 'resource_objects' => "resource_objects#index"
    get 'resource_objects/library/clause' => "resource_objects#library_clause"
    get 'resource_objects/library/clause_revision' => "resource_objects#library_clause_revision"
    get 'resource_objects/library/clause_variation' => "resource_objects#library_clause_variation"
    get 'resource_objects/library/indicator' => "resource_objects#library_indicator"
    get 'resource_objects/library/indicator_value' => "resource_objects#library_indicator_value"
    get 'resource_objects/library/prescription' => "resource_objects#library_prescription"
    get 'resource_objects/library/prescription_revision' => "resource_objects#library_prescription_revision"
    get 'resource_objects/library/regulation' => "resource_objects#library_regulation"
    get 'resource_objects/library/section' => "resource_objects#library_section"
    get 'resource_objects/procurement_document/clat' => "resource_objects#pd_clat"
    get 'resource_objects/procurement_document/clause' => "resource_objects#pd_clause"
    get 'resource_objects/procurement_document/indicator' => "resource_objects#pd_indicator"
    get 'resource_objects/procurement_document/indicator_value' => "resource_objects#pd_indicator_value"
    get 'resource_objects/procurement_document/procurement_document' => "resource_objects#pd_procurement_document"
    get 'resource_objects/procurement_document/regulation' => "resource_objects#pd_regulation"

    # Resources Documentation
    get 'resources' => "resources#index"
    get 'resources/library_clauses' => "resources#library_clauses"
    get 'resources/library_clause' => "resources#library_clause"
    get 'resources/library_clause_revisions' => "resources#library_clause_revisions"
    get 'resources/library_indicators' => "resources#library_indicators"
    get 'resources/library_indicator' => "resources#library_indicator"
    get 'resources/library_prescriptions' => "resources#library_prescriptions"
    get 'resources/library_prescription' => "resources#library_prescription"
    get 'resources/library_prescription_revisions' => "resources#library_prescription_revisions"
    get 'resources/library_regulations' => "resources#library_regulations"
    get 'resources/library_regulation' => "resources#library_regulation"
    get 'resources/library_sections' => "resources#library_sections"
    get 'resources/library_section' => "resources#library_section"
    get 'resources/procurement_document/clats' => "resources#pd_clats"
    get 'resources/procurement_document/clat' => "resources#pd_clat"
    get 'resources/procurement_document/clat_create' => "resources#pd_clat_create"
    get 'resources/procurement_document/clat_expire' => "resources#pd_clat_expire"
    get 'resources/procurement_document/clat_extend' => "resources#pd_clat_extend"
    get 'resources/procurement_document/clauses' => "resources#pd_clauses"
    get 'resources/procurement_document/clause' => "resources#pd_clause"
    get 'resources/procurement_document/clause_create' => "resources#pd_clause_create"
    get 'resources/procurement_document/clause_update' => "resources#pd_clause_update"
    get 'resources/procurement_document/clause_delete' => "resources#pd_clause_delete"
    get 'resources/procurement_document/indicators' => "resources#pd_indicators"
    get 'resources/procurement_document/indicator' => "resources#pd_indicator"
    get 'resources/procurement_document/indicators_update' => "resources#pd_indicators_update"
    get 'resources/procurement_document/indicator_update' => "resources#pd_indicator_update"
    get 'resources/procurement_document/procurement_documents' => "resources#pd_procurement_documents"
    get 'resources/procurement_document/procurement_document' => "resources#pd_procurement_document"
    get 'resources/procurement_document/procurement_document_create' => "resources#pd_procurement_document_create"
    get 'resources/procurement_document/procurement_document_update' => "resources#pd_procurement_document_update"
    get 'resources/procurement_document/procurement_document_launch_gui' => "resources#pd_procurement_document_launch_gui"
    get 'resources/procurement_document/regulations' => "resources#pd_regulations"
    get 'resources/procurement_document/regulations_update' => "resources#pd_regulations_update"
    get 'resources/general/timestamp' => "resources#general_timestamp"

    get 'authentication/request_types' => "auth#request_types"
    get 'authentication/signature' => "auth#signature"

    get 'guides/create_procurement_document' => "guides#create_procurement_document"
    get 'guides/specify_indicators' => "guides#specify_indicators"
    get 'guides/specify_regulations' => "guides#specify_regulations"
    get 'guides/launch_gui' => "guides#launch_gui"
    get 'guides/api_environments' => 'guides#api_environments'
    get 'guides/overview' => "guides#overview"

    # Tutorials
    get 'tutorials/create_procurement_document' => "tutorials#create_procurement_document"
    get 'tutorials/applying_regulations' => "tutorials#applying_regulations"
    get 'tutorials/clats_and_how_to_use_them' => "tutorials#clats_and_how_to_use_them"
    get 'tutorials/how_to_specify_indicators' => "tutorials#how_to_specify_indicators"

    # Api Documentation
    get 'api/errors' => "api#errors"
  end

  namespace "v2" do
    root :to => "welcome#index"

    get 'whats_new' => "welcome#whats_new"

    # Resource Objects Documentation
    resources :resource_objects, :only => [:index] do
      get 'clause', :on => :collection
      get 'clause_revision', :on => :collection
      get 'indicator', :on => :collection
      get 'indicator_value', :on => :collection
      get 'prescription', :on => :collection
      get 'prescription_revision', :on => :collection
      get 'regulation', :on => :collection
      get 'section', :on => :collection
      get 'document', :on => :collection
      get 'document_regulation', :on => :collection
      get 'document_question', :on => :collection
    end

    # Resources Documentation
    get 'resources' => "resources#index"
    get 'resources/library_clauses' => "resources#library_clauses"
    get 'resources/library_clause' => "resources#library_clause"
    get 'resources/library_clause_revisions' => "resources#library_clause_revisions"
    get 'resources/library_indicators' => "resources#library_indicators"
    get 'resources/library_indicator' => "resources#library_indicator"
    get 'resources/library_prescriptions' => "resources#library_prescriptions"
    get 'resources/library_prescription' => "resources#library_prescription"
    get 'resources/library_prescription_revisions' => "resources#library_prescription_revisions"
    get 'resources/library_regulations' => "resources#library_regulations"
    get 'resources/library_regulation' => "resources#library_regulation"
    get 'resources/library_sections' => "resources#library_sections"
    get 'resources/library_section' => "resources#library_section"
    get 'resources/procurement_document/clats' => "resources#pd_clats"
    get 'resources/procurement_document/clat' => "resources#pd_clat"
    get 'resources/procurement_document/clat_create' => "resources#pd_clat_create"
    get 'resources/procurement_document/clat_expire' => "resources#pd_clat_expire"
    get 'resources/procurement_document/clat_extend' => "resources#pd_clat_extend"
    get 'resources/procurement_document/clauses' => "resources#pd_clauses"
    get 'resources/procurement_document/clause' => "resources#pd_clause"
    get 'resources/procurement_document/clause_create' => "resources#pd_clause_create"
    get 'resources/procurement_document/clause_update' => "resources#pd_clause_update"
    get 'resources/procurement_document/clause_delete' => "resources#pd_clause_delete"
    get 'resources/procurement_document/indicators' => "resources#pd_indicators"
    get 'resources/procurement_document/indicator' => "resources#pd_indicator"
    get 'resources/procurement_document/indicators_update' => "resources#pd_indicators_update"
    get 'resources/procurement_document/indicator_update' => "resources#pd_indicator_update"
    get 'resources/procurement_document/procurement_documents' => "resources#pd_procurement_documents"
    get 'resources/procurement_document/procurement_document' => "resources#pd_procurement_document"
    get 'resources/procurement_document/procurement_document_create' => "resources#pd_procurement_document_create"
    get 'resources/procurement_document/procurement_document_update' => "resources#pd_procurement_document_update"
    get 'resources/procurement_document/procurement_document_launch_gui' => "resources#pd_procurement_document_launch_gui"
    get 'resources/procurement_document/regulations' => "resources#pd_regulations"
    get 'resources/procurement_document/regulations_update' => "resources#pd_regulations_update"
    get 'resources/general/timestamp' => "resources#general_timestamp"

    get 'authentication' => "auth#index"

    get 'guides/create_procurement_document' => "guides#create_procurement_document"
    get 'guides/specify_indicators' => "guides#specify_indicators"
    get 'guides/specify_regulations' => "guides#specify_regulations"
    get 'guides/launch_gui' => "guides#launch_gui"
    get 'guides/api_environments' => 'guides#api_environments'
    get 'guides/overview' => "guides#overview"

    # Tutorials
    get 'tutorials/create_procurement_document' => "tutorials#create_procurement_document"
    get 'tutorials/applying_regulations' => "tutorials#applying_regulations"
    get 'tutorials/clats_and_how_to_use_them' => "tutorials#clats_and_how_to_use_them"
    get 'tutorials/how_to_specify_indicators' => "tutorials#how_to_specify_indicators"

    # Api Documentation
    get 'api/errors' => "api#errors"
  end

  root :to => "v1/welcome#index"

end

app/models/v2/clause.rb
class V2::Clause < V2::Resource::Base
  has_field 'id',               type: :numeric, description: 'A unique identifier for the clause'
  has_field 'number',           type: :string,  description: 'Clause number'
  has_field 'referenceAllowed', type: :boolean, description: 'If clause can be incorporated by reference'
  has_field 'provision',        type: :boolean, description: 'If this is a clause'
  has_field 'regulation',       type: :object,  description: 'Parent Regulation object'
  has_field 'section',          type: :object,  description: 'UCF Section object of the clause'
  has_field 'clauseVariation',  type: :object,  description: 'Alternate or Deviation'
  has_field 'revision',         type: :object,  description: 'Clause Revision object'

  @example = {
    id: 1, 
    number: '2.201', 
    referenceAllowed: true,
    provision: false,
    regulation: V2::Regulation.compact,
    section: V2::Section.compact,
    clauseVariation: V2::ClauseVariation.example,
    revision: V2::ClauseRevision.example
  }

end

app/models/v2/clause_revision.rb
class V2::ClauseRevision < V2::Resource::Base
  has_field 'id',        type: :numeric, description: 'A unique identifier for the revision'
  has_field 'title',     type: :string,  description: 'Clause title'
  has_field 'body',      type: :string,  description: 'Clause text (HTML)'
  has_field 'fillins',   type: :array,   complete: :some, description: 'Array of Fill-ins for the clause'
  has_field 'startDate', type: :string,  description: 'Effective Start Date'
  has_field 'endDate',   type: :string,  description: 'Effective End Date'
  has_field 'editable',  type: :boolean, description: 'Whether the clause is editable'

  @example = {
    id: 1,
    title: 'Clause Title',
    body: '... clause text ...',
    fillins: [V2::Fillin.example], 
    startDate: '2011-01-01',
    endDate: '2013-12-31',
    editable: false
  }

end

app/models/v2/clause_variation.rb
class V2::ClauseVariation < V2::Resource::Base
  has_field 'type', type: :string, description: 'Variation Type'
  has_field 'name', type: :string, description: 'Variation Name'
  
  @example = {
    type: 'Alternate', 
    name: 'Alternate I'
  }
  
end

app/models/v2/fillin.rb
class V2::Fillin < V2::Resource::Base
  has_field 'id',       type: :numeric, description: 'A unique identifier for the fill-in'
  has_field 'name',     type: :numeric, description: 'Fill-In name'
  has_field 'source',   type: :numeric, description: 'Government or Vendor'
  has_field 'dataType', type: :numeric, description: 'Text, Number, Currency, Date, etc.'
  has_field 'options',  type: :numeric, complete: :some, description: 'Pre-defined options for the fill-in'

  @example = {
    id: 1,
    name: 'Agency',
    source: 'Government',
    dataType: 'text',
    options: ["NASA", "Department of Defense", "Coast Guard"]
  }
  
end

app/models/v2/indicator.rb
class V2::Indicator < V2::Resource::Base
  has_field 'id',         type: :numeric, description: 'A unique identifier for the indicator'
  has_field 'name',       type: :string,  description: 'Indicator name'
  has_field 'dataType',   type: :string,  description: 'Data Type'
  has_field 'constraint', type: :string,  description: 'Constraint'
  has_field 'values',     type: :array,   complete: :some, description: 'Pre-defined values'
  
  @example = {
    id: 1, 
    name: 'Document Type',
    dataType: 'text',
    constraint: 'Pick Many',
    values: [ V2::IndicatorValue.example ]
  }
end

app/models/v2/indicator_value.rb
class V2::IndicatorValue < V2::Resource::Base
  has_field 'id',    type: :numeric, description: 'A unique identifier for the indicator value'
  has_field 'value', type: :string,  description: 'value'
  
  @example = {
    id: 1,
    value: 'Award'
  }
  
end

app/models/v2/prescription.rb
class V2::Prescription < V2::Resource::Base
  has_field 'id',         type: :numeric, description: 'A unique identifier for the prescription'
  has_field 'number',     type: :string,  description: 'Prescription number'
  has_field 'regulation', type: :object,  description: 'Parent Regulation object'
  has_field 'revision',   type: :object,  description: 'Prescription Revision object'

  @example = {
    id: 1, 
    number: '2.201', 
    regulation: V2::Regulation.compact,
    revision: V2::PrescriptionRevision.example
  }

end

app/models/v2/prescription_revision.rb
class V2::PrescriptionRevision < V2::Resource::Base
  has_field 'id',        type: :numeric, description: 'A unique identifier for the revision'
  has_field 'body',      type: :string,  description: 'Prescription text (HTML)'
  has_field 'startDate', type: :string,  description: 'Effective Start Date'
  has_field 'endDate',   type: :string,  description: 'Effective End Date'
  
  @example = {
    id: 1, 
    body: '... prescription text ...', 
    startDate: '2011-01-01',
    endDate: '2013-12-31'
  }
  
end

app/models/v2/regulation.rb
class V2::Regulation < V2::Resource::Base
  has_field 'id',    type: :numeric, compact: :always, description: 'A unique identifier for the regulation'
  has_field 'name',  type: :string,  compact: :never,  description: 'Regulation name'
  has_field 'title', type: :string,  compact: :always, description: 'Regulation title'
  has_field 'url',   type: :string,  compact: :never,  description: 'URL of regulation website'
  
  @example = {
    id: 1, 
    name: 'Federal Acquisition Regulation', 
    title: 'FAR', 
    url: 'https://www.acquisition.gov/far'
  }
  
  @compact = {
    id: 1,
    title: 'FAR'
  }

end

app/models/v2/resource.rb
module V2::Resource
  autoload :RequestParam, 'v2/resource/request_param'
end

app/models/v2/resource/base.rb
module V2::Resource
  class Base
    include RequestParam
  end
end

app/models/v2/resource/field.rb
module V2::Resource
  module Field
    
    def self.included(base)
      base.extend(ClassMethods)
    end
    
    module ClassMethods

      def has_field(name, options = {})
        @_fields ||= {}
        @_fields[name] = {} if @_fields[name].nil?
        @_fields[name][:type] = options[:type] || :string
        @_fields[name][:compact] = options[:compact] || :never
        @_fields[name][:complete] = options[:complete] || :always
        @_fields[name][:example] = options[:example]
        @_fields[name][:description] = options[:description] || "" 
      end
      
      def fields
        @_fields
      end
    end
  end
end

app/models/v2/resource/request_param.rb
module V2::Resource
  module RequestParam
    
    def self.included(base)
      base.extend(ClassMethods)
    end
    
    module ClassMethods

      def request_param(name, options = {})
        @_request_params ||= {}
        @_request_params[name] = {} if @_request_params[name].nil?
        @_request_params[name][:type] = options[:type] || :string
        @_request_params[name][:compact] = options[:compact] || :never
        @_request_params[name][:complete] = options[:complete] || :always
        @_request_params[name][:example] = options[:example]
        @_request_params[name][:description] = options[:description] || "" 
      end
      
      def request_params
        @_request_params
      end
    end
    
  end
end

app/models/v2/resource_object.rb
module V2::ResourceObject
  autoload :Field, 'v2/resource_object/field'
  autoload :Base, 'v2/resource_object/base'
end

app/models/v2/resource_object/base.rb
module V2::ResourceObject
  class Base
    include Field
    
    @example = nil
    @compact = nil
    
    def self.example
      @example
    end
    
    def self.compact
      @compact
    end
    
  end
end

app/views/v2/guides/api_environments.html.erb
<% content_for :page_header do %>
  <br />
  <ul class="breadcrumb">
    <li><%= link_to 'Documentation', v2_root_path %> <span class="divider">/</span></li>
    <li class="active">Getting Started: API Environments</li>
  </ul>
  <div class="row">
    <div class="span12">
      <h1>API Environments</h1>
    </div>
  </div>
<% end %>

<table class="table">
  <thead>
    <th>Name</th>
    <th>URL</th>
    <th>Description</th>
  </thead>

  <tbody>
    <tr>
      <td>Integration</td>
      <td>http://integration.clause-logic.com/</td>
      <td>Integration Environment</td>
    </tr>
    <tr>
      <td>Production</td>
      <td>https://clauselogic.altess.army.mil/</td>
      <td>Production Environment</td>
    </tr>
  </tbody>
</table>

app/views/v2/guides/create_procurement_document.html.erb
<% content_for :page_header do %>
  <br />
  <ul class="breadcrumb">
    <li><%= link_to 'Documentation', v2_root_path %> <span class="divider">/</span></li>
    <li class="active">Getting Started: Create a Procurement Document</li>
  </ul>
  <div class="row">
    <div class="span12">
      <h1>Creating a Procurement Document</h1>
    </div>
  </div>
<% end %>

<h3>Required Information</h3>
<p>The Number is the only attribute that is needed in order to create a Procurement Document:</p>

<table class="table">
  <tr>
    <td>Number</td>
    <td>
      <p>The Procurement Document Number (i.e. Contract Number)</p>
      <p>The procurement document is created using the following resource: <%= link_to 'POST procurement_documents', v2_resources_procurement_document_procurement_document_create_path %></p>
    </td>
  </tr>
</table>
<br />
<h3>Additional Information</h3>
<p>
  Once created, you will need to provide additional information about the procurement document in order for the Clause Logic Service to determine the appropriate clauses/provisions for the procurement document.
</p>
<table class="table">
  <tr>
    <td>Regulations</td>
    <td>
      <p>Specify which regulations (FAR, DFARS, etc.) apply to the procurement document.</p>
      <p>Regulations can be specified using the following resource: <%= link_to 'PUT procurement_documents/:token/regulations', v2_resources_procurement_document_regulations_update_path %></p>
    </td>
  </tr>
  <tr>
    <td>Indicators</td>
    <td>
      <p>Specify details about the procurement document: Total Value, Type of Contract, Procedures Used, etc.</p>
      <p>Indicators can be specified using the following resource: <%= link_to 'PUT procurement_documents/:token/indicators', v2_resources_procurement_document_indicators_update_path %></p>
    </td>
  </tr>
</table>

app/views/v2/guides/launch_gui.html.erb
<% content_for :page_header do %>
  <br />
  <ul class="breadcrumb">
    <li><%= link_to 'Documentation', v2_root_path %> <span class="divider">/</span></li>
    <li class="active">Getting Started: Launch GUI</li>
  </ul>
  <div class="row">
    <div class="span12">
      <h1>Launch the Clause Logic GUI</h1>
    </div>
  </div>
<% end %>

<p>After a procurement document has been created and the indicators and regulations have been specified, the Clause Logic GUI needs to be launched to provide any additional procurement document information and to determine appropriate clauses/provisions.</p>
<br />
<h3>How to launch the GUI</h3>
<p>Use the following resource to obtain the unique Launch URL for the procurement document: <%= link_to 'GET procurement_documents/:token/launch_gui', v2_resources_procurement_document_procurement_document_launch_gui_path %>.</p>
<br />
<h3>Clause Logic Access Token (CLAT) Required</h3>
<p>Launching the Clause Logic GUI requires a <%= link_to 'Clause Logic Access Token (CLAT)', v2_resource_objects_procurement_document_clat_path %>.  Use the following resource to obtain a CLAT: <%= link_to 'POST procurement_documents/:token/clats', v2_resources_procurement_document_clat_create_path %>. A CLAT can only launch the GUI one time.  In order to relaunch the GUI, you must expire the current CLAT and create a new one.</p>

app/views/v2/guides/overview.html.erb
<% content_for :page_header do %>
  <br />
  <ul class="breadcrumb">
    <li><%= link_to 'Documentation', v2_root_path %> <span class="divider">/</span></li>
    <li class="active">Getting Started: API Overview</li>
  </ul>
  <div class="row">
    <div class="span12">
      <h1>REST API Overview</h1>
    </div>
  </div>
<% end %>

<h3>About the API</h3>
<p>
  Below is a list of information about the Clause Logic REST API.<br />
  <ul>
    <li>All requests to the API must use the <strong>HTTPS</strong> protocol.</li>
    <li>Only registered applications will be allowed to access the API.</li>
    <li>There are three types of authenticated requests.  See the Authentication documentation for more information.</li>
    <li>All requests/responses use the <strong>XML</strong> format.</li>
    <li>The following HTTP Methods are used in requests: GET, POST, PUT, DELETE.</li>
  </ul>
      
</p>

app/views/v2/guides/specify_indicators.html.erb
<% content_for :page_header do %>
  <br />
  <ul class="breadcrumb">
    <li><%= link_to 'Documentation', v2_root_path %> <span class="divider">/</span></li>
    <li class="active">Guides: Specify Indicators</li>
  </ul>
  <div class="row">
    <div class="span12">
      <h1>Specifying Indicators</h1>
    </div>
  </div>
<% end %>

<p>Indicators provide information about the procurement document: Total Value, Type of Contract, Procedures Used, etc. There are 3 types of Indicators: PICK_MANY, PICK_ONE, and NONE.</p>
<br />
<h3>Types of Indicators</h3>
<h4>PICK_MANY</h4>
<p>A Pick Many Indicator has a list of pre-defined values to choose from.  As the name suggests, you may pick more than one of the available values.</p>

<h4>PICK_ONE</h4>
<p>A Pick One Indicator also has a list of pre-defined values to choose from, but only one value may be selected.</p>

<h4>NONE</h4>
<p>A NONE Indicator does not have pre-defined values and only one value may be provided.</p>

<br />
<h3>How to Specify Indicators</h3>
<p>There are two ways to specify indicators: API or Clause Logic GUI.  From the API, Indicators can be specified using the following resource: <%= link_to 'PUT procurement_documents/:token/indicators', v2_resources_procurement_document_indicators_update_path %>.  Indicator values specified through the API cannot be modified from the Clause Logic GUI. </p>
<br />
<h3>Clause Logic Access Token (CLAT) Required</h3>
<p>Any modification to a procurement document requires a <%= link_to 'Clause Logic Access Token (CLAT)', v2_resource_objects_procurement_document_clat_path %>.  Use the following resource to obtain a CLAT: <%= link_to 'POST procurement_documents/:token/clats', v2_resources_procurement_document_clat_create_path %>.</p>

app/views/v2/guides/specify_regulations.html.erb
<% content_for :page_header do %>
  <br />
  <ul class="breadcrumb">
    <li><%= link_to 'Documentation', v2_root_path %> <span class="divider">/</span></li>
    <li class="active">Getting Started: Specify Regulations</li>
  </ul>
  <div class="row">
    <div class="span12">
      <h1>Specifying Regulations</h1>
    </div>
  </div>
<% end %>

<p>The Clause Logic Service supports a wide variety of regulations (FAR, DFARS, etc.).  In order to determine appropriate clauses/provisions for the procurement document, it is important to specify which regulations apply.</p>
<br />
<h3>How to Specify Regulations</h3>
<p>There are two ways to specify regulations: API or Clause Logic GUI.  From the API, Regulations can be specified using the following resource: <%= link_to 'PUT procurement_documents/:token/regulations', resources_procurement_document_regulations_update_path %>.  Regulations specified through the API cannot be modified from the Clause Logic GUI. If no regulations are specified, Clause Logic will default to using FAR.</p>
<br/>
<h3>Clause Logic Access Token (CLAT) Required</h3>
<p>
  Any modification to a procurement document requires a <%= link_to 'Clause Logic Access Token (CLAT)', resource_objects_procurement_document_clat_path %>.  Use the following resource to obtain a CLAT: <%= link_to 'POST procurement_documents/:token/clats', resources_procurement_document_clat_create_path %>.
</p>